apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
  namespace: aws-ebs-csi-driver
spec:
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce